services:
  kibana:
    image: docker.elastic.co/kibana/kibana-wolfi:9.2.3
    restart: always
    mem_limit: '1gb'
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: kibanaBloodline
      TZ: Asia/Shanghai
      I18N_LOCALE: zh-CN
      XPACK_FLEET_ISAIRGAPPED: true
      XPACK_FLEET_REGISTRYURL: http://elastic-package-registry:8080
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: min-32-byte-long-strong-encryption-key
    volumes:
      - kibanadata:/usr/share/kibana/data
    ports:
      - "14321:5601"
    networks:
      - elasticsearch_elastic-net
volumes:
  kibanadata:
networks:
  elasticsearch_elastic-net:
    external: true
