services:
  elastic-agent:
    image: docker.elastic.co/elastic-agent/elastic-agent-wolfi:9.2.3
    user: root
    restart: always
    environment:
      FLEET_ENROLL: 1
      FLEET_URL: "https://fleet-server:8220"
      FLEET_ENROLLMENT_TOKEN: "SjlPLWw1c0JXd1lHa3diUWl6ZWo6MG5OaldHdjNSMU1ObS1kRmhESTlxZw=="
      TZ: Asia/Shanghai
      FLEET_INSECURE: true
    networks:
      - elasticsearch_elastic-net
    ports:
      - "24321:8200"
networks:
  elasticsearch_elastic-net:
    external: true
