services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:9.2.3
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    environment:
      ELASTIC_PASSWORD: es01Bloodline
      discovery.type: single-node
      xpack.security.http.ssl.enabled: false
      TZ: Asia/Shanghai
    restart: always
    mem_limit: '1gb'
    networks:
      - elastic-net
volumes:
  esdata01:
networks:
  elastic-net:
