services:
  fleet-server:
    image: docker.elastic.co/elastic-agent/elastic-agent-wolfi:9.2.3
    restart: always
    environment:
      FLEET_SERVER_ENABLE: 1
      FLEET_SERVER_ELASTICSEARCH_HOST: "http://es01:9200"
      FLEET_SERVER_SERVICE_TOKEN: "AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE3Njc3Nzc0OTA2MDk6V0o0Y2hRbklRcHU4SVpLX1JFNE8yQQ"
      FLEET_SERVER_POLICY_ID: "fleet-server-policy"
      TZ: Asia/Shanghai
    networks:
      - elasticsearch_elastic-net
networks:
  elasticsearch_elastic-net:
    external: true
