services:
  elastic-package-registry:
    image: docker.elastic.co/package-registry/distribution:9.2.3
    restart: always
    environment:
      TZ: Asia/Shanghai
    networks:
      - elasticsearch_elastic-net
networks:
  elasticsearch_elastic-net:
    external: true
