spring:
  application:
    name: shardingsphere-smoke-tests
  threads:
    virtual:
      enabled: true
  main:
    keep-alive: true
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:demo.yaml
